### ISSUE TITLE
Use style.css to write basic style

### ISSUE THREAD

**Issue by michael-dev-pilotin** [Pilot-in/PiloPress-Addon#15]
Remove this filter in **/includes/class-tailwind.php**:

add_filter( 'acf/load_value/name=pip_tailwind_style_components', array( $this, 'tw_style_components' ), 20, 1 );

And write basic style directly in style.css file at the root of the theme.

**Comment by damien-pilot-in** [comment]
I'm planning on updating `style.css` content in the theme folder on the first load _(with the old style config we had)_ if there is no specific style declaration in the file _(by checking if there is `{` character)_.

**Comment by maelys-pilotin** [comment]
CSS added in `style.css` file in the [Starter Theme](https://github.com/Pilot-in/Starter-Theme) directly
