### ISSUE TITLE
JS variables not declared

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress-Addon#17]
You check if 2 jquery elements exists but you don't declared them before causing an error.

https://github.com/Pilot-in/PiloPress-Addon/blob/88d41972b75f61763a599fc7ae5c44be4b5f6466/assets/js/pip-layout-copy-vars.js#L20-L26

**Comment by damien-pilot-in** [comment]
Use `const` or `let` or `var` otherwise it's going to be some variables in the global DOM.

**Comment by maelys-pilotin** [comment]
Fixed
